version: '3.8'

services:
  php:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
      - /path/to/your/folder:/var/www/html/files  # Remplacez /path/to/your/folder par le chemin où vous souhaitez créer les dossiers et fichiers
    networks:
      - file_net

  nginx:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - file_net

networks:
  file_net:
